apiVersion: v1
kind: Service
metadata:
  name: yarn-resourcemanager
  namespace: hadoop
spec:
  type: NodePort
  selector:
    app: yarn-resourcemanager
  ports:
    - name: scheduler
      port: 8030
      targetPort: 8030
    - name: resourcetracker
      port: 8031
      targetPort: 8031
    - name: rpc
      port: 8032
      targetPort: 8032
    - name: admin
      port: 8033
      targetPort: 8033
    - name: web
      port: 8090
      targetPort: 8090
      nodePort: 30890

