apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-datanode-pv-worker-02
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hdfs
  local:
    path: /var/lib/hadoop-k8s/hdfs-data-worker-02
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-02

